import {
  siC, siCplusplus, siCss, siExpress, siGit, siGithub,
  siHtml5, siIntellijidea, siJavascript, siMongodb, siMysql,
  siN8n, siNextdotjs, siNodedotjs, siPython, siReact,
  // ── Additional verified simple-icons slugs ──
  siTypescript, siRust, siGo, siKotlin, siSwift, siRuby, siPhp, siScala,
  siElixir, siErlang, siHaskell, siSolidity, siClojure, siDart, siLua,
  siJulia, siOcaml, siPerl, siR, siDotnet, siDeno, siBun, siGnubash,
  siVuedotjs, siSvelte, siAngular, siSolid,
  siAstro, siRemix, siGatsby, siNestjs, siNuxt, siQuasar, siElectron,
  siExpo, siFlutter, siAndroidstudio, siApple, siLinux, siUbuntu,
  siDebian, siFedora, siArchlinux, siCentos, siRedhat, siKalilinux,
  siDocker, siKubernetes, siHelm, siTerraform, siAnsible, siGrafana,
  siPrometheus, siRedis, siPostgresql, siSqlite, siApachecassandra,
  siApachecouchdb, siInfluxdb, siCockroachlabs,
  siElasticsearch, siApachekafka, siRabbitmq, siNginx, siApache,
  siApacheairflow, siGraphql, siApollographql, siThreedotjs,
  siTailwindcss, siBootstrap, siSass, siWebpack, siVite, siBabel,
  siEslint, siPrettier, siStorybook, siFigma, siJest, siCypress,
  siPuppeteer, siTestinglibrary, siGitlab, siGithubactions, siJenkins,
  siCircleci, siTravisci, siVercel, siNetlify, siCloudflare, siDigitalocean,
  siGooglecloud, siCloudflareworkers, siCloudflarepages, siFlydotio,
  siRender, siRailway, siScaleway, siHetzner, siOvh, siContabo, siVultr,
  siPytorch, siTensorflow, siKeras, siOnnx, siScikitlearn, siNumpy,
  siPandas, siPlotly, siStreamlit, siGradio, siOpencv, siFastapi,
  siFlask, siDjango, siSpring, siSpringboot, siFastify, siExpress as siExpressIcon,
  siPrisma, siSupabase, siPlanetscale, siFirebase, siAppwrite, siDirectus,
  siStrapi, siSanity, siContentful, siGhost, siWordpress, siShopify,
  siStripe, siPaypal, siCoinbase, siBinance, siEthereum, siSolana,
  siChainlink, siLangchain, siLangchaincorporate, siAnthropic, siHuggingface,
  siOllama, siMistralai, siPerplexity, siPoe, siReplicate, siMetabase,
  siAirbyte, siSnowflake, siDatabricks, siClickhouse, siDuckdb,
  siNeo4j, siArangodb, siMilvus, siQdrant,
  siZapier, siMake, siIfttt, siN8n as siN8nIcon, siSelenium, siGatling,
  siLocust, siJenkins as siJenkinsIcon, siDatadog, siNewrelic, siSentry,
  siKibana, siLogstash, siHashicorp, siVault, siConsul, siNomad,
  siProxmox, siNeovim, siVim, siCodeigniter,
  siGodotengine, siUnity, siUnrealengine, siBlender, siObsstudio,
  siFramer, siWebflow, siWix, siSquarespace, siNotion, siDiscord,
  siTelegram, siWhatsapp, siX, siYoutube, siTwitch,
  siSpotify, siFlutter as siFlutterIcon, siExpo as siExpoIcon,
} from "simple-icons/icons";
import {
  Bot, BrainCircuit, Brain, Database, Sparkles,
  Boxes, Code2, Cloud, Flame, Layers, Leaf, Server,
  GitBranch, Container, Cpu, Terminal, TerminalSquare, Workflow,
  Network, Zap, Atom, Binary, Hash, Globe, MessageSquare,
  Settings, Wrench, Rocket, Box, Circle, Triangle, Square,
  Hexagon, Gauge, LineChart, GitCommitHorizontal,
  FileCode, Braces, FunctionSquare, MemoryStick, HardDrive, Bot as BotIcon,
  Sparkle, PenTool, Image, Video, Mic, Camera, Music, PenLine,
  Database as DbIcon,
} from "lucide-react";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faJava } from "@fortawesome/free-brands-svg-icons";

export type Brand =
  | { type: "svg"; path: string; hex: string }
  | { type: "fa"; icon: typeof faJava; hex: string }
  | { type: "lucide"; Icon: typeof Database; hex: string }
  | { type: "raw"; svg: string };

// Official Microsoft VS Code logo (multicolor) inlined as raw SVG so we don't
// ship a separate PNG/asset file. The mask id is made unique by the caller.
export const VSCODE_SVG = `<svg viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
<mask id="vscode-mask" mask-type="alpha" maskUnits="userSpaceOnUse" x="0" y="0" width="100" height="100">
<path fill-rule="evenodd" clip-rule="evenodd" d="M70.9119 99.3171C72.4869 99.9307 74.2828 99.8914 75.8725 99.1264L96.4608 89.2197C98.6242 88.1787 100 85.9892 100 83.5872V16.4133C100 14.0113 98.6243 11.8218 96.4609 10.7808L75.8725 0.873756C73.7862 -0.130129 71.3446 0.11576 69.5135 1.44695C69.252 1.63711 69.0028 1.84943 68.769 2.08341L29.3551 38.0415L12.1872 25.0096C10.589 23.7965 8.35363 23.8959 6.86933 25.2461L1.36303 30.2549C-0.452552 31.9064 -0.454633 34.7627 1.35853 36.417L16.2471 50.0001L1.35853 63.5832C-0.454633 65.2374 -0.452552 68.0938 1.36303 69.7453L6.86933 74.7541C8.35363 76.1043 10.589 76.2037 12.1872 74.9905L29.3551 61.9587L68.769 97.9167C69.3925 98.5406 70.1246 99.0104 70.9119 99.3171ZM75.0152 27.2989L45.1091 50.0001L75.0152 72.7012V27.2989Z" fill="white"/>
</mask>
<g mask="url(#vscode-mask)">
<path d="M96.4614 10.7962L75.8569 0.875542C73.4719 -0.272773 70.6217 0.211611 68.75 2.08333L1.29858 63.5832C-0.515693 65.2373 -0.513607 68.0937 1.30308 69.7452L6.81272 74.754C8.29793 76.1042 10.5347 76.2036 12.1338 74.9905L93.3609 13.3699C96.086 11.3026 100 13.2462 100 16.6667V16.4275C100 14.0265 98.6246 11.8378 96.4614 10.7962Z" fill="#0065A9"/>
<path d="M96.4614 89.2038L75.8569 99.1245C73.4719 100.273 70.6219 99.7884 68.75 97.9167L1.29858 36.4169C-0.515693 34.7627 -0.513607 31.9063 1.30308 30.2548L6.81272 25.246C8.29793 23.8958 10.5347 23.7964 12.1338 25.0095L93.3609 86.6301C96.086 88.6974 100 86.7538 100 83.3334V83.5726C100 85.9735 98.6246 88.1622 96.4614 89.2038Z" fill="#007ACC"/>
<path d="M75.8578 99.1263C73.4721 100.274 70.6219 99.7885 68.75 97.9166C71.0564 100.223 75 98.5895 75 95.3278V4.67213C75 1.41039 71.0564 -0.223106 68.75 2.08329C70.6219 0.211402 73.4721 -0.273666 75.8578 0.873633L96.4587 10.7807C98.6234 11.8217 100 14.0112 100 16.4132V83.5871C100 85.9891 98.6234 88.1786 96.4586 89.2196L75.8578 99.1263Z" fill="#1F9CF0"/>
</g>
</svg>`;

export const skillBrands: Record<string, Brand> = {
  C: { type: "svg", path: siC.path, hex: siC.hex },
  "C++": { type: "svg", path: siCplusplus.path, hex: siCplusplus.hex },
  Python: { type: "svg", path: siPython.path, hex: siPython.hex },
  // Java brand mark from Font Awesome.
  Java: { type: "fa", icon: faJava, hex: "E76F00" },
  HTML: { type: "svg", path: siHtml5.path, hex: siHtml5.hex },
  CSS: { type: "svg", path: siCss.path, hex: "1572B6" },
  JavaScript: { type: "svg", path: siJavascript.path, hex: siJavascript.hex },
  "React.js": { type: "svg", path: siReact.path, hex: siReact.hex },
  "Next.js": { type: "svg", path: siNextdotjs.path, hex: "FFFFFF" },
  "Express.js": { type: "svg", path: siExpress.path, hex: "CBD5E1" },
  "Node.js": { type: "svg", path: siNodedotjs.path, hex: siNodedotjs.hex },
  MySQL: { type: "svg", path: siMysql.path, hex: siMysql.hex },
  MongoDB: { type: "svg", path: siMongodb.path, hex: siMongodb.hex },
  Git: { type: "svg", path: siGit.path, hex: siGit.hex },
  GitHub: { type: "svg", path: siGithub.path, hex: "E6EDF3" },
  // Official Microsoft VS Code logo, inlined as raw multicolor SVG.
  "VS Code": { type: "raw", svg: VSCODE_SVG },
  "IntelliJ IDEA": { type: "svg", path: siIntellijidea.path, hex: "FE315D" },
  "n8n automation": { type: "svg", path: siN8n.path, hex: siN8n.hex },
};

export const extraIcons: Record<string, Brand> = {
  // ── Databases / data (generic + brand) ──
  SQL: { type: "lucide", Icon: Database, hex: "38BDF8" },
  JDBC: { type: "lucide", Icon: Database, hex: "5FA04E" },
  "REST API": { type: "lucide", Icon: Network, hex: "F89820" },
  GraphQL: { type: "svg", path: siGraphql.path, hex: siGraphql.hex },
  PostgreSQL: { type: "svg", path: siPostgresql.path, hex: siPostgresql.hex },
  Redis: { type: "svg", path: siRedis.path, hex: siRedis.hex },
  SQLite: { type: "svg", path: siSqlite.path, hex: siSqlite.hex },
  Cassandra: { type: "svg", path: siApachecassandra.path, hex: siApachecassandra.hex },
  CouchDB: { type: "svg", path: siApachecouchdb.path, hex: siApachecouchdb.hex },
  InfluxDB: { type: "svg", path: siInfluxdb.path, hex: siInfluxdb.hex },
  CockroachDB: { type: "svg", path: siCockroachlabs.path, hex: siCockroachlabs.hex },
  Elasticsearch: { type: "svg", path: siElasticsearch.path, hex: siElasticsearch.hex },
  Neo4j: { type: "svg", path: siNeo4j.path, hex: siNeo4j.hex },
  ArangoDB: { type: "svg", path: siArangodb.path, hex: siArangodb.hex },
  Milvus: { type: "svg", path: siMilvus.path, hex: siMilvus.hex },
  Qdrant: { type: "svg", path: siQdrant.path, hex: siQdrant.hex },
  Snowflake: { type: "svg", path: siSnowflake.path, hex: siSnowflake.hex },
  Databricks: { type: "svg", path: siDatabricks.path, hex: siDatabricks.hex },
  ClickHouse: { type: "svg", path: siClickhouse.path, hex: siClickhouse.hex },
  DuckDB: { type: "svg", path: siDuckdb.path, hex: siDuckdb.hex },
  Planetscale: { type: "svg", path: siPlanetscale.path, hex: siPlanetscale.hex },
  Supabase: { type: "svg", path: siSupabase.path, hex: siSupabase.hex },
  Firebase: { type: "svg", path: siFirebase.path, hex: siFirebase.hex },
  Appwrite: { type: "svg", path: siAppwrite.path, hex: siAppwrite.hex },
  Prisma: { type: "svg", path: siPrisma.path, hex: siPrisma.hex },
  Drizzle: { type: "lucide", Icon: Leaf, hex: "C5F74F" },
  "Vector DB": { type: "lucide", Icon: Boxes, hex: "8B5CF6" },

  // ── AI / LLM / ML ──
  "Generative AI": { type: "lucide", Icon: Sparkles, hex: "A855F7" },
  "Prompt Engineering": { type: "lucide", Icon: Bot, hex: "38BDF8" },
  LLMs: { type: "lucide", Icon: BrainCircuit, hex: "F472B6" },
  PyTorch: { type: "svg", path: siPytorch.path, hex: siPytorch.hex },
  TensorFlow: { type: "svg", path: siTensorflow.path, hex: siTensorflow.hex },
  Keras: { type: "svg", path: siKeras.path, hex: siKeras.hex },
  ONNX: { type: "svg", path: siOnnx.path, hex: siOnnx.hex },
  scikitlearn: { type: "svg", path: siScikitlearn.path, hex: siScikitlearn.hex },
  NumPy: { type: "svg", path: siNumpy.path, hex: siNumpy.hex },
  Pandas: { type: "svg", path: siPandas.path, hex: siPandas.hex },
  Plotly: { type: "svg", path: siPlotly.path, hex: siPlotly.hex },
  Streamlit: { type: "svg", path: siStreamlit.path, hex: siStreamlit.hex },
  Gradio: { type: "svg", path: siGradio.path, hex: siGradio.hex },
  OpenCV: { type: "svg", path: siOpencv.path, hex: siOpencv.hex },
  FastAPI: { type: "svg", path: siFastapi.path, hex: siFastapi.hex },
  LangChain: { type: "svg", path: siLangchain.path, hex: siLangchain.hex },
  Anthropic: { type: "svg", path: siAnthropic.path, hex: siAnthropic.hex },
  "Hugging Face": { type: "svg", path: siHuggingface.path, hex: siHuggingface.hex },
  Ollama: { type: "svg", path: siOllama.path, hex: siOllama.hex },
  "Mistral AI": { type: "svg", path: siMistralai.path, hex: siMistralai.hex },
  Perplexity: { type: "svg", path: siPerplexity.path, hex: siPerplexity.hex },
  Poe: { type: "svg", path: siPoe.path, hex: siPoe.hex },
  Replicate: { type: "svg", path: siReplicate.path, hex: siReplicate.hex },
  Metabase: { type: "svg", path: siMetabase.path, hex: siMetabase.hex },
  Airbyte: { type: "svg", path: siAirbyte.path, hex: siAirbyte.hex },
  Weaviate: { type: "lucide", Icon: Boxes, hex: "22AD9C" },
  Pinecone: { type: "lucide", Icon: Boxes, hex: "3B00CC" },
  dbt: { type: "lucide", Icon: GitBranch, hex: "FF694B" },
  OpenAI: { type: "lucide", Icon: Bot, hex: "10A37F" },
  "Computer Vision": { type: "lucide", Icon: Image, hex: "22D3EE" },

  // ── Automation / integration ──
  "n8n automation": { type: "svg", path: siN8n.path, hex: siN8n.hex },
  Zapier: { type: "svg", path: siZapier.path, hex: siZapier.hex },
  Make: { type: "svg", path: siMake.path, hex: siMake.hex },
  IFTTT: { type: "svg", path: siIfttt.path, hex: siIfttt.hex },
  Selenium: { type: "svg", path: siSelenium.path, hex: siSelenium.hex },
  Gatling: { type: "svg", path: siGatling.path, hex: siGatling.hex },
  Locust: { type: "svg", path: siLocust.path, hex: siLocust.hex },
  "Workflow Automation": { type: "lucide", Icon: Workflow, hex: "A855F7" },

  // ── Languages (additional) ──
  TypeScript: { type: "svg", path: siTypescript.path, hex: siTypescript.hex },
  Rust: { type: "svg", path: siRust.path, hex: siRust.hex },
  Go: { type: "svg", path: siGo.path, hex: siGo.hex },
  Kotlin: { type: "svg", path: siKotlin.path, hex: siKotlin.hex },
  Swift: { type: "svg", path: siSwift.path, hex: siSwift.hex },
  Ruby: { type: "svg", path: siRuby.path, hex: siRuby.hex },
  PHP: { type: "svg", path: siPhp.path, hex: siPhp.hex },
  Scala: { type: "svg", path: siScala.path, hex: siScala.hex },
  Elixir: { type: "svg", path: siElixir.path, hex: siElixir.hex },
  Erlang: { type: "svg", path: siErlang.path, hex: siErlang.hex },
  Haskell: { type: "svg", path: siHaskell.path, hex: siHaskell.hex },
  Solidity: { type: "svg", path: siSolidity.path, hex: siSolidity.hex },
  Clojure: { type: "svg", path: siClojure.path, hex: siClojure.hex },
  Dart: { type: "svg", path: siDart.path, hex: siDart.hex },
  Lua: { type: "svg", path: siLua.path, hex: siLua.hex },
  Julia: { type: "svg", path: siJulia.path, hex: siJulia.hex },
  OCaml: { type: "svg", path: siOcaml.path, hex: siOcaml.hex },
  Perl: { type: "svg", path: siPerl.path, hex: siPerl.hex },
  Rlang: { type: "svg", path: siR.path, hex: siR.hex },
  ".NET": { type: "svg", path: siDotnet.path, hex: siDotnet.hex },
  Deno: { type: "svg", path: siDeno.path, hex: siDeno.hex },
  Bun: { type: "svg", path: siBun.path, hex: siBun.hex },
  Bash: { type: "svg", path: siGnubash.path, hex: siGnubash.hex },

  // ── Frameworks / frontend ──
  Vue: { type: "svg", path: siVuedotjs.path, hex: siVuedotjs.hex },
  Svelte: { type: "svg", path: siSvelte.path, hex: siSvelte.hex },
  Angular: { type: "svg", path: siAngular.path, hex: siAngular.hex },
  SolidJS: { type: "svg", path: siSolid.path, hex: siSolid.hex },
  Astro: { type: "svg", path: siAstro.path, hex: siAstro.hex },
  Remix: { type: "svg", path: siRemix.path, hex: siRemix.hex },
  Gatsby: { type: "svg", path: siGatsby.path, hex: siGatsby.hex },
  "NestJS": { type: "svg", path: siNestjs.path, hex: siNestjs.hex },
  Nuxt: { type: "svg", path: siNuxt.path, hex: siNuxt.hex },
  Quasar: { type: "svg", path: siQuasar.path, hex: siQuasar.hex },
  Electron: { type: "svg", path: siElectron.path, hex: siElectron.hex },
  Expo: { type: "svg", path: siExpo.path, hex: siExpo.hex },
  Flutter: { type: "svg", path: siFlutter.path, hex: siFlutter.hex },
  "React Native": { type: "lucide", Icon: Atom, hex: "61DAFB" },
  "Three.js": { type: "svg", path: siThreedotjs.path, hex: siThreedotjs.hex },

  // ── Styling / build ──
  "Tailwind CSS": { type: "svg", path: siTailwindcss.path, hex: siTailwindcss.hex },
  Bootstrap: { type: "svg", path: siBootstrap.path, hex: siBootstrap.hex },
  Sass: { type: "svg", path: siSass.path, hex: siSass.hex },
  Webpack: { type: "svg", path: siWebpack.path, hex: siWebpack.hex },
  Vite: { type: "svg", path: siVite.path, hex: siVite.hex },
  Babel: { type: "svg", path: siBabel.path, hex: siBabel.hex },
  ESLint: { type: "svg", path: siEslint.path, hex: siEslint.hex },
  Prettier: { type: "svg", path: siPrettier.path, hex: siPrettier.hex },
  Storybook: { type: "svg", path: siStorybook.path, hex: siStorybook.hex },
  Figma: { type: "svg", path: siFigma.path, hex: siFigma.hex },
  Jest: { type: "svg", path: siJest.path, hex: siJest.hex },
  Cypress: { type: "svg", path: siCypress.path, hex: siCypress.hex },
  Puppeteer: { type: "svg", path: siPuppeteer.path, hex: siPuppeteer.hex },
  "Testing Library": { type: "svg", path: siTestinglibrary.path, hex: siTestinglibrary.hex },

  // ── Backend / APIs ──
  Flask: { type: "svg", path: siFlask.path, hex: siFlask.hex },
  Django: { type: "svg", path: siDjango.path, hex: siDjango.hex },
  Spring: { type: "svg", path: siSpring.path, hex: siSpring.hex },
  "Spring Boot": { type: "svg", path: siSpringboot.path, hex: siSpringboot.hex },
  Fastify: { type: "svg", path: siFastify.path, hex: siFastify.hex },

  // ── DevOps / cloud / infra ──
  Docker: { type: "svg", path: siDocker.path, hex: siDocker.hex },
  Kubernetes: { type: "svg", path: siKubernetes.path, hex: siKubernetes.hex },
  Helm: { type: "svg", path: siHelm.path, hex: siHelm.hex },
  Terraform: { type: "svg", path: siTerraform.path, hex: siTerraform.hex },
  Ansible: { type: "svg", path: siAnsible.path, hex: siAnsible.hex },
  Grafana: { type: "svg", path: siGrafana.path, hex: siGrafana.hex },
  Prometheus: { type: "svg", path: siPrometheus.path, hex: siPrometheus.hex },
  Nginx: { type: "svg", path: siNginx.path, hex: siNginx.hex },
  Apache: { type: "svg", path: siApache.path, hex: siApache.hex },
  Kafka: { type: "svg", path: siApachekafka.path, hex: siApachekafka.hex },
  RabbitMQ: { type: "svg", path: siRabbitmq.path, hex: siRabbitmq.hex },
  "Apache Airflow": { type: "svg", path: siApacheairflow.path, hex: siApacheairflow.hex },
  Vercel: { type: "svg", path: siVercel.path, hex: siVercel.hex },
  Netlify: { type: "svg", path: siNetlify.path, hex: siNetlify.hex },
  Cloudflare: { type: "svg", path: siCloudflare.path, hex: siCloudflare.hex },
  "Cloudflare Workers": { type: "svg", path: siCloudflareworkers.path, hex: siCloudflareworkers.hex },
  "Cloudflare Pages": { type: "svg", path: siCloudflarepages.path, hex: siCloudflarepages.hex },
  "Google Cloud": { type: "svg", path: siGooglecloud.path, hex: siGooglecloud.hex },
  DigitalOcean: { type: "svg", path: siDigitalocean.path, hex: siDigitalocean.hex },
  Render: { type: "svg", path: siRender.path, hex: siRender.hex },
  Railway: { type: "svg", path: siRailway.path, hex: siRailway.hex },
  Scaleway: { type: "svg", path: siScaleway.path, hex: siScaleway.hex },
  Hetzner: { type: "svg", path: siHetzner.path, hex: siHetzner.hex },
  OVH: { type: "svg", path: siOvh.path, hex: siOvh.hex },
  Contabo: { type: "svg", path: siContabo.path, hex: siContabo.hex },
  Vultr: { type: "svg", path: siVultr.path, hex: siVultr.hex },
  "Fly.io": { type: "svg", path: siFlydotio.path, hex: siFlydotio.hex },
  AWS: { type: "lucide", Icon: Cloud, hex: "FF9900" },
  Azure: { type: "lucide", Icon: Cloud, hex: "0078D4" },
  Oracle: { type: "lucide", Icon: Cloud, hex: "F80000" },
  "CI/CD": { type: "lucide", Icon: GitCommitHorizontal, hex: "22C55E" },
  Jenkins: { type: "svg", path: siJenkins.path, hex: siJenkins.hex },
  GitLab: { type: "svg", path: siGitlab.path, hex: siGitlab.hex },
  "GitHub Actions": { type: "svg", path: siGithubactions.path, hex: siGithubactions.hex },
  CircleCI: { type: "svg", path: siCircleci.path, hex: siCircleci.hex },
  TravisCI: { type: "svg", path: siTravisci.path, hex: siTravisci.hex },

  // ── Monitoring / observability ──
  Datadog: { type: "svg", path: siDatadog.path, hex: siDatadog.hex },
  NewRelic: { type: "svg", path: siNewrelic.path, hex: siNewrelic.hex },
  Sentry: { type: "svg", path: siSentry.path, hex: siSentry.hex },
  Kibana: { type: "svg", path: siKibana.path, hex: siKibana.hex },
  Logstash: { type: "svg", path: siLogstash.path, hex: siLogstash.hex },
  HashiCorp: { type: "svg", path: siHashicorp.path, hex: siHashicorp.hex },
  Vault: { type: "svg", path: siVault.path, hex: siVault.hex },
  Consul: { type: "svg", path: siConsul.path, hex: siConsul.hex },
  Nomad: { type: "svg", path: siNomad.path, hex: siNomad.hex },

  // ── OS / environments ──
  Linux: { type: "svg", path: siLinux.path, hex: siLinux.hex },
  Ubuntu: { type: "svg", path: siUbuntu.path, hex: siUbuntu.hex },
  Debian: { type: "svg", path: siDebian.path, hex: siDebian.hex },
  Fedora: { type: "svg", path: siFedora.path, hex: siFedora.hex },
  Arch: { type: "svg", path: siArchlinux.path, hex: siArchlinux.hex },
  CentOS: { type: "svg", path: siCentos.path, hex: siCentos.hex },
  "Red Hat": { type: "svg", path: siRedhat.path, hex: siRedhat.hex },
  "Kali Linux": { type: "svg", path: siKalilinux.path, hex: siKalilinux.hex },
  Apple: { type: "svg", path: siApple.path, hex: siApple.hex },
  Android: { type: "svg", path: siAndroidstudio.path, hex: siAndroidstudio.hex },
  Proxmox: { type: "svg", path: siProxmox.path, hex: siProxmox.hex },
  Neovim: { type: "svg", path: siNeovim.path, hex: siNeovim.hex },
  Vim: { type: "svg", path: siVim.path, hex: siVim.hex },
  CodeIgniter: { type: "svg", path: siCodeigniter.path, hex: siCodeigniter.hex },

  // ── Gaming / 3D / creative ──
  Godot: { type: "svg", path: siGodotengine.path, hex: siGodotengine.hex },
  Unity: { type: "svg", path: siUnity.path, hex: siUnity.hex },
  "Unreal Engine": { type: "svg", path: siUnrealengine.path, hex: siUnrealengine.hex },
  Blender: { type: "svg", path: siBlender.path, hex: siBlender.hex },
  OBS: { type: "svg", path: siObsstudio.path, hex: siObsstudio.hex },
  Framer: { type: "svg", path: siFramer.path, hex: siFramer.hex },
  Webflow: { type: "svg", path: siWebflow.path, hex: siWebflow.hex },
  Wix: { type: "svg", path: siWix.path, hex: siWix.hex },
  Squarespace: { type: "svg", path: siSquarespace.path, hex: siSquarespace.hex },
  Notion: { type: "svg", path: siNotion.path, hex: siNotion.hex },
  Discord: { type: "svg", path: siDiscord.path, hex: siDiscord.hex },
  Telegram: { type: "svg", path: siTelegram.path, hex: siTelegram.hex },
  WhatsApp: { type: "svg", path: siWhatsapp.path, hex: siWhatsapp.hex },
  X: { type: "svg", path: siX.path, hex: siX.hex },
  YouTube: { type: "svg", path: siYoutube.path, hex: siYoutube.hex },
  Twitch: { type: "svg", path: siTwitch.path, hex: siTwitch.hex },
  Spotify: { type: "svg", path: siSpotify.path, hex: siSpotify.hex },

  // ── CMS / content / commerce ──
  WordPress: { type: "svg", path: siWordpress.path, hex: siWordpress.hex },
  Shopify: { type: "svg", path: siShopify.path, hex: siShopify.hex },
  Stripe: { type: "svg", path: siStripe.path, hex: siStripe.hex },
  PayPal: { type: "svg", path: siPaypal.path, hex: siPaypal.hex },
  Coinbase: { type: "svg", path: siCoinbase.path, hex: siCoinbase.hex },
  Binance: { type: "svg", path: siBinance.path, hex: siBinance.hex },
  Ethereum: { type: "svg", path: siEthereum.path, hex: siEthereum.hex },
  Solana: { type: "svg", path: siSolana.path, hex: siSolana.hex },
  Chainlink: { type: "svg", path: siChainlink.path, hex: siChainlink.hex },
  Sanity: { type: "svg", path: siSanity.path, hex: siSanity.hex },
  Contentful: { type: "svg", path: siContentful.path, hex: siContentful.hex },
  Ghost: { type: "svg", path: siGhost.path, hex: siGhost.hex },
  Strapi: { type: "svg", path: siStrapi.path, hex: siStrapi.hex },
  Directus: { type: "svg", path: siDirectus.path, hex: siDirectus.hex },
};

/** Resolve the brand/logo for a skill name, or undefined if none is mapped. */
export function brandFor(text: string): Brand | undefined {
  return skillBrands[text] ?? extraIcons[text];
}

/** Sorted list of every icon key available in the picker (skillBrands + extraIcons). */
export const ICON_KEYS: string[] = Array.from(
  new Set([...Object.keys(skillBrands), ...Object.keys(extraIcons)]),
).sort();
